[2024-12-19T09:00:02.959+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T09:00:02.997+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-06-06T00:00:00+00:00 [queued]>
[2024-12-19T09:00:03.019+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-06-06T00:00:00+00:00 [queued]>
[2024-12-19T09:00:03.024+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T09:00:03.138+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-06-06 00:00:00+00:00
[2024-12-19T09:00:03.163+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'third_task', 'scheduled__2024-06-06T00:00:00+00:00', '--job-id', '2798', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpbgqbnkcm']
[2024-12-19T09:00:03.166+0000] {standard_task_runner.py:105} INFO - Job 2798: Subtask third_task
[2024-12-19T09:00:03.162+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=11963) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T09:00:03.180+0000] {standard_task_runner.py:72} INFO - Started process 11987 to run task
[2024-12-19T09:00:03.342+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.third_task scheduled__2024-06-06T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T09:00:03.533+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-06T00:00:00+00:00'
[2024-12-19T09:00:03.537+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T09:00:03.565+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T09:00:03.582+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task and I will be executed at the same time as the second task.']
[2024-12-19T09:00:03.639+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T09:00:03.643+0000] {subprocess.py:106} INFO - I am the third task and I will be executed at the same time as the second task.
[2024-12-19T09:00:03.648+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T09:00:03.693+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T09:00:03.694+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=third_task, run_id=scheduled__2024-06-06T00:00:00+00:00, execution_date=20240606T000000, start_date=20241219T090003, end_date=20241219T090003
[2024-12-19T09:00:03.777+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T09:00:03.814+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T09:00:03.822+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
