[2024-12-19T09:01:42.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T09:01:42.615+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-12-19T09:01:42.628+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-12-19T09:01:42.629+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T09:01:42.709+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-11-26 00:00:00+00:00
[2024-12-19T09:01:42.730+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14072) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T09:01:42.735+0000] {standard_task_runner.py:72} INFO - Started process 14077 to run task
[2024-12-19T09:01:42.735+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'third_task', 'scheduled__2024-11-26T00:00:00+00:00', '--job-id', '3310', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmphueto21u']
[2024-12-19T09:01:42.741+0000] {standard_task_runner.py:105} INFO - Job 3310: Subtask third_task
[2024-12-19T09:01:42.880+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.third_task scheduled__2024-11-26T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T09:01:43.079+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T00:00:00+00:00'
[2024-12-19T09:01:43.081+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T09:01:43.128+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T09:01:43.132+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task and I will be executed at the same time as the second task.']
[2024-12-19T09:01:43.177+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T09:01:43.180+0000] {subprocess.py:106} INFO - I am the third task and I will be executed at the same time as the second task.
[2024-12-19T09:01:43.181+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T09:01:43.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T09:01:43.270+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=third_task, run_id=scheduled__2024-11-26T00:00:00+00:00, execution_date=20241126T000000, start_date=20241219T090142, end_date=20241219T090143
[2024-12-19T09:01:43.384+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T09:01:43.406+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
