[2024-12-19T08:57:54.212+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T08:57:54.233+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2024-12-19T08:57:54.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.third_task scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2024-12-19T08:57:54.250+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T08:57:54.286+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2023-10-18 00:00:00+00:00
[2024-12-19T08:57:54.301+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'third_task', 'scheduled__2023-10-18T00:00:00+00:00', '--job-id', '2096', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpd_lb0md9']
[2024-12-19T08:57:54.304+0000] {standard_task_runner.py:105} INFO - Job 2096: Subtask third_task
[2024-12-19T08:57:54.297+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9117) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T08:57:54.307+0000] {standard_task_runner.py:72} INFO - Started process 9131 to run task
[2024-12-19T08:57:54.407+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.third_task scheduled__2023-10-18T00:00:00+00:00 [running]> on host 8d142e9c83a7
[2024-12-19T08:57:54.501+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-18T00:00:00+00:00'
[2024-12-19T08:57:54.502+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T08:57:54.520+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T08:57:54.522+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the third task and I will be executed at the same time as the second task.']
[2024-12-19T08:57:54.536+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T08:57:54.537+0000] {subprocess.py:106} INFO - I am the third task and I will be executed at the same time as the second task.
[2024-12-19T08:57:54.538+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T08:57:54.561+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T08:57:54.562+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=third_task, run_id=scheduled__2023-10-18T00:00:00+00:00, execution_date=20231018T000000, start_date=20241219T085754, end_date=20241219T085754
[2024-12-19T08:57:54.618+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T08:57:54.632+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T08:57:54.634+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
